config/routes.rb
TurbolinksSample::Application.routes.draw do
  get "redirect/index", as: 'redirect' 

  get "campaign/campaign1", as: 'campaign1'
  get "campaign/campaign2", as: 'campaign2' 

  resources :users
  root 'users#index'

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/campaign_controller.rb
class CampaignController < ApplicationController
  def campaign1
  end

  def campaign2
  end
end

app/controllers/redirect_controller.rb
class RedirectController < ApplicationController
  def index  
    url = params[:next_url] || root_url 
    redirect_to url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper 
  def title(title)
    content_for(:title) { title }
  end 

  def description(description)
    content_for(:description) { description }
  end 

  def keywords(keywords)
    content_for(:keywords) { keywords }
  end  
end

app/views/campaign/campaign1.html.erb
<% title('campaign1') %> 
<% description('campaign1') %> 
<% keywords('campaign1') %> 
<p>campaign1</p>

app/views/campaign/campaign2.html.erb
<% title('campaign2') %> 
<% description('campaign2') %> 
<% keywords('campaign2') %> 
<p>campaign2</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>  

  <title><%= yield :title %></title>
  <meta name="description" content="<%= yield :description %>">
  <meta name="keywords" content="<%= yield :keywords %>">  
  <script> 
    $(document).ready(function(){ 
      console.log("jquery ready");
      alert("jquery ready");
    }); 
  
    $(document).on("page:change", function(event){
      console.log("page:change");
    });  

    $(document).on("page:fetch", function(event){
      console.log("page:fetch");
    });  

    $(document).on("page:receive", function(event){
      console.log("page:receive");
    });  

    $(document).on("page:load", function(event){
      console.log("page:load");
    }); 
  </script>
  </script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% title('edit user') %> 
<% description('edit user') %> 
<% keywords('edit user') %> 

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% title('top page') %> 
<% description('top page') %> 
<% keywords('index') %> 

<h3>Link to campaign page</h3> 
<%= link_to 'campaign1', campaign1_url %><br />
<%= link_to 'campaign2(no turboklink)', campaign2_url, "data-no-turbolink" => '1' %>
<br /><br />
<h3>Redirect</h3> 
<%= link_to 'redirect to google', redirect_url(next_url: 'https://www.google.co.jp/') %><br />
<%= link_to 'redirect to campaing1', redirect_url(next_url: campaign1_url) %><br />
<br /><br />
<h3>Listing users</h3> 
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.age %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>
<% title('new user') %> 
<% description('new user') %> 
<% keywords('new user') %> 

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p> 

<% title('show user') %> 
<% description('show user') %> 
<% keywords('show user') %> 

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>